data:
  bias_pattern: bias_pattern.png
  chunk_dirs:
    high_res: high_res_data
    low_res: low_res_data
    test_x: test_X
    test_y: test_y
    train_x: train_X
    train_y: train_y
  directory: data
  quantization:
    dynamic_range: true
    enabled: true
    max_value: 1.0
    min_value: 0.0
    precision: fp8
data_generation:
  center_temp_range:
  - 0.6
  - 0.9
  daily_low_hour: 4
  daily_peak_hour: 14
  falloff_rate: 1.3
  hours: 8760
  image_size:
  - 48
  - 48
  outer_temp_range:
  - 0.2
  - 0.5
neural_network:
  dropout_rate: 0.2
  early_stopping_patience: 10
  epochs: 100
  hidden_layers:
  - 128
  - 64
  learning_rate: 0.001
regression:
  batch_size: 2304
  loss_type: mse
  regressor_type: linear
  spatial_window:
  - 3
  - 3
  stride: 1
  temporal_window:
  - -24
  - -23
  - -3
  - -2
  - -1
  train_size: 0.8
visualization:
  colormap: viridis
  dpi: 100
  figure_size:
  - 10
  - 8
